language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

notifications:
  email:
    on_success: never

script:
  - cargo test --verbose --all
  - cargo test --verbose --all --no-default-features
