[package]
authors = ["Garrett Berg <googberg@gmail.com>"]
name = "path_abs"
version = "0.1.0"

[dependencies]
serde = ">=1.0"
serde_derive = "1.0.27"
stfu8 = ">=0.2"
walkdir = "2.0.1"

[dev-dependencies]
pretty_assertions = "0.4.1"
serde_json = "1.0.9"
tempdir = "0.3.5"
